SYNCQT.HEADER_FILES = gl2.h gl2ext.h gl2platform.h 
SYNCQT.INJECTED_HEADER_FILES = 
SYNCQT.HEADER_CLASSES = 
SYNCQT.PRIVATE_HEADER_FILES = 
SYNCQT.INJECTED_PRIVATE_HEADER_FILES = 
SYNCQT.QPA_HEADER_FILES = 
SYNCQT.CLEAN_HEADER_FILES = 
SYNCQT.INJECTIONS = 
